server:
  port: 0

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true